// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "mag-nat1@yandex.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/get/key": {
            "get": {
                "tags": [
                    "Авторизация"
                ],
                "summary": "Запрос открытого ключа сервера",
                "responses": {
                    "200": {
                        "description": "Отправка ключа"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервиса"
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Авторизация"
                ],
                "summary": "Авторизация пользователя в микросервисе. Данные должны быть зашифрованы открытым ключём сервера.",
                "parameters": [
                    {
                        "description": "Логи и пароль пользователя в формате json",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.LoginPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация",
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "Токен авторизации"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка при расшифровке тела запроса"
                    },
                    "401": {
                        "description": "Логин или пароль не найден"
                    },
                    "422": {
                        "description": "Ошибка при конвертации json"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервиса"
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Авторизация"
                ],
                "summary": "Регистрация нового пользователя. Данные должны быть зашифрованы открытым ключём сервера.",
                "parameters": [
                    {
                        "description": "Логин и пароль пользователя в формате json",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.LoginPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация пользователя",
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "Токен авторизации"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка при расшифровке тела запроса"
                    },
                    "409": {
                        "description": "Такой логин уже используется другим пользователем."
                    },
                    "422": {
                        "description": "Ошибка при конвертации json"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервиса."
                    }
                }
            }
        }
    },
    "definitions": {
        "server.LoginPassword": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API для сервера менеджера паролей GophKeeper.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GophKeeper API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
