basePath: /
definitions:
  server.LoginPassword:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: mag-nat1@yandex.ru
    name: API Support
  title: GophKeeper API
  version: "1.0"
paths:
  /api/get/key:
    get:
      responses:
        "200":
          description: Отправка ключа
        "500":
          description: Внутренняя ошибка сервиса
      summary: Запрос открытого ключа сервера
      tags:
      - Авторизация
  /api/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Логи и пароль пользователя в формате json
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/server.LoginPassword'
      responses:
        "200":
          description: Успешная авторизация
          headers:
            Authorization:
              description: Токен авторизации
              type: string
        "400":
          description: Ошибка при расшифровке тела запроса
        "401":
          description: Логин или пароль не найден
        "422":
          description: Ошибка при конвертации json
        "500":
          description: Внутренняя ошибка сервиса
      summary: Авторизация пользователя в микросервисе. Данные должны быть зашифрованы
        открытым ключём сервера.
      tags:
      - Авторизация
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Логин и пароль пользователя в формате json
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/server.LoginPassword'
      responses:
        "200":
          description: Успешная регистрация пользователя
          headers:
            Authorization:
              description: Токен авторизации
              type: string
        "400":
          description: Ошибка при расшифровке тела запроса
        "409":
          description: Такой логин уже используется другим пользователем.
        "422":
          description: Ошибка при конвертации json
        "500":
          description: Внутренняя ошибка сервиса.
      summary: Регистрация нового пользователя. Данные должны быть зашифрованы открытым
        ключём сервера.
      tags:
      - Авторизация
securityDefinitions:
  ApiKeyAuth:
    description: API для сервера менеджера паролей GophKeeper.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
